### ISSUE TITLE
i haven't pay sheet after call requestSubscription in IOS 

### ISSUE THREAD

**Issue by hamidAslami** [dooboolab/flutter_inapp_purchase#271] opened 2021-03-08 09:22 UTC
i am using from flutter_inapp_purchase for **auto renewal Subscription** and when i call requestSubscription in my code i haven't  pay sheet but received a callback on _purchaseUpdatedSubscription with received a old expired item.

note: in first payment i have pay sheet and buy processes is successfully and when auto renewal period(6 auto renewal) is finished i try to buy in second i have this issue 
```
  Future<Null> buyProduct() async {
    try {
      IAPItem item = _products.first;
      await FlutterInappPurchase.instance.requestSubscription(item.productId);
    } catch (error) {
      print("error on buyProduct: $error");
    }
  }
```
  
```
      _purchaseUpdatedSubscription =
        FlutterInappPurchase.purchaseUpdated.listen((productItem) async {
      print('purchase-updated: $productItem');

    });
```
  
  

 i use **flutter_inapp_purchase ^3.0.1** version and my Platforms is **IOS** and I Tested on **Real Device**

**Comment by d9media** [comment] 2021-03-11 01:44
I think I have the same problem. 

Item expired but still comes back as restored

**Comment by sundong212** [comment] 2021-03-30 03:10
I have the same issue. The second or third time I made purchase, it returned a receipt and then for a while, the console in Xcode is logging `Restored` and `paymentQueueRestoreCompletedTransactionsFinished`.

**Comment by DmitriyGribennikov** [comment] 2021-04-15 16:03
Have same issue. 
Version of  flutter_inapp_purchase  is 3.0.1.

**Comment by ErrorCode-404** [comment] 2021-04-26 09:56
Facing the same issue.
Using flutter_inapp_purchase: 5.0.1 and recently updated to Flutter 2.

**Comment by StefanZeuch** [comment] 2021-04-26 13:56
I have the same issue on v5.0.1.
Is this just an issue on Sandbox?

**Comment by ErrorCode-404** [comment] 2021-04-26 16:10
Really hope so :) otherwise it will be a deal breaker.

**Comment by just-kip** [comment] 2021-05-15 11:11
Faced the same problem

**Comment by heilmela** [comment] 2021-06-03 14:40
Faceing the same problem 
`requestSubscription` does not return and log prints 'Restored'

**Comment by heilmela** [comment] 2021-06-04 11:49
It seems to me that this issue occurs when immediately before calling `requestSubscription` either `getPurchaseHistory` or `getAvailablePurchases` is invoked. 
Then `requestSubscription` is stuck and no pay sheet is shown

**Comment by krzaklus** [comment] 2021-06-07 16:07
@heilmela I have the same problem like you. I notice that if I run getAvailablePurchases, and next the requestSubscript they will never end, is stuck.  Do you have any idea how to solve it?

**Comment by ErrorCode-404** [comment] 2021-06-07 16:22
So I found out that calling clearTransactionIOS right before requestSubscription does always present me a purchase pay sheet now. Don't know if other kind of products e.g. consumables will also work.

Plugin Version: 5.0.1
Flutter Version:  2.2.1
iOS Version: 14.6
Device: iPhone X
Migrated to Null-Safety: yes

**Comment by krzaklus** [comment] 2021-06-07 21:01
@ErrorCode-404 I tried calling clearTransactionIOS  before requestSubscription but it's not work for my, but i notice some other behavior. If I force delay 10 seconds after execute getAvailablePurchases and then run requestSubscription dialog are display. This work every time.

Solution:

// execute method to get available purchase
getAvailablePurchases 

// force delay 10 seconds
delay(10000)

// execute properly method to buy subscription
requestSubscription  

I know it's dirty solution, but it's work for me. For now i prevent user to click button to buy subscription before delay 10 seconds was executed. I'm pretty sure that is a bug in library, but I'dont know how to solve it elegant.


Plugin Version: 5.0.1
Flutter Version: 2.2.1
iOS Version: 14.6
Device: iPhone SE
Migrated to Null-Safety: yes

**Comment by ErrorCode-404** [comment] 2021-06-08 10:14
@krzaklus Why do you need to call getAvailablePurchases because it only delivers a list of PurchasedItem which are used to know if or what the user has bought. Okay it maybe used to downgrade or upgrade the subscription but nevertheless you need to call getProducts or in this case getSubscriptions to load the purchaseable products or subscriptions.

Because the products must be loaded first before they can be used to make purchases especially for iOS. So what you do now is loading them and waiting for the completion (your delay). Then you buy via requestSubscription.

So what I do is the following (simplified):

```
class _SubscriptionPurchaseScreenState
    extends State<SubscriptionPurchaseScreen> {

BehaviorSubject<List<IAPItem>?> subscriptionProductsSubject =
      BehaviorSubject.seeded(null);

@override
  void initState() {
FlutterInappPurchase.instance.initConnection.then((value) {
        List<IAPItem> subs = await FlutterInappPurchase.instance.getSubscriptions([subscriptionIdMonthly, subscriptionIdYearly]);
subscriptionProductsSubject.add(subs);
    });
    super.initState();
  }

  @override
  void dispose() {
    FlutterInappPurchase.instance.endConnection
    super.dispose();
  }

...

  void onBuySubscriptionPressed() async{
       await FlutterInappPurchase.instance.clearTransactionIOS();
       await FlutterInappPurchase.instance.requestSubscription(subscriptionProductsSubject.value!.first);
  }
}

```

I hope this will help.

**Comment by krzaklus** [comment] 2021-06-08 11:40
@ErrorCode-404 I know that, I'dont send everytime getAvailablePurchases() only when I detect that subscription are expired (for example once a month in month subscription) and I want to know it is that subscription are restored, only this time I run getAvailablePurchases() and when  I do it without force daley i can't use requestSubscription. This flow what you described works for me everytiem, only this specyfic flow what I described didint work for me without delay.

I didn't use validateReceipt so maybe this is a clue of my problem, when I used validateReceipt I will I get clear information (Android and IOS) is the subscription is not expired?

**Comment by heilmela** [comment] 2021-06-08 11:51
Neither calling `clearTransactionIOS()` nor a timeout is changing things for me (i would strongly discourage such "fixes" anyway). 

Since `getAvailablePurchases()` on IOS restores purchases, is it required to call `finishTransaction()` (which the official Apple doc suggests) and should they appear in the updateListener with `TransactionState.purchased` ?

 I dont receive any item on the update stream and calling `finishTransaction()` on the restored items causes the updateListener to receive a `null` value. Either restoring purchases is not working as intended or the documentation is too inaccurate

**Comment by alex-lechner** [comment] 2021-08-12 10:04
I have the same problem. Any fix for this?

**Comment by sherwin** [comment] 2021-11-16 05:56
The problem remains.

**Closed** 2021-11-24 01:04 UTC
Labels: no-issue-activity

**Comment by Hacklone** [comment] 2022-01-21 11:58
Same for me

**Comment by vijaycoderkube** [comment] 2023-09-25 12:41
print('Before purchase');
PurchasedItem purchased = await FlutterInappPurchase.buyProduct(item.productId);
print('After purchase');

Why this log is not printed 'After purchase'?

**Comment by enesakbal** [comment] 2024-11-08 12:19
When I add this lines problem is solved
```
final pendingTransactions = await flutterInappPurchase.getPendingTransactionsIOS();

for (final e in pendingTransactions ?? <PurchasedItem>[]) {
        await flutterInappPurchase.finishTransaction(}
```
