### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#13] opened 2018-08-10 16:17 UTC
```
I/FlutterActivityDelegate(14203): onResume setting current activity to this
I/Activity(14203): Activity.onPostResume() called
I/OpenGLRenderer(14203): Initialized EGL, version 1.4
I/Timeline(14203): Timeline: Activity_idle id: android.os.BinderProxy@e23be97 time:114541679
W/BillingClient(14203): Billing service disconnected.
D/FlutterInappPurchasePlugin(14203): billing client disconnected
D/AndroidRuntime(14203): Shutting down VM
E/AndroidRuntime(14203): FATAL EXCEPTION: main
E/AndroidRuntime(14203): Process: com.ifthen.whencoin, PID: 14203
E/AndroidRuntime(14203): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(14203): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
E/AndroidRuntime(14203): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(14203): 	at com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin$2.onBillingSetupFinished(FlutterInappPurchasePlugin.java:94)
E/AndroidRuntime(14203): 	at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected(BillingClientImpl.java:903)
E/AndroidRuntime(14203): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1386)
E/AndroidRuntime(14203): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1403)
E/AndroidRuntime(14203): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(14203): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14203): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(14203): 	at android.app.ActivityThread.main(ActivityThread.java:5422)
E/AndroidRuntime(14203): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14203): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14203): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
E/AndroidRuntime(14203): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by dooboolab** [comment] 2018-08-10 19:10
@lukepighetti Ok. Maybe somewhere it isn't `thread safe` I'll look into this one. Hope you can contribute either.

**Comment by lukepighetti** [comment] 2018-08-11 01:47
Unfortunately I have no experience with Java/Android... I apologize!

**Comment by dooboolab** [comment] 2018-08-11 07:07
@lukepighetti No problem. We can monitor this problem if someone else is facing the same. Could you share some other information like when did this problem occured? What is the senario to reproduce this?

**Comment by lukepighetti** [comment] 2018-08-11 20:11
I am sorry I did not remember to write down details. If I come across it again I will be sure to record everything!

**Comment by dooboolab** [comment] 2018-08-11 21:27
@lukepighetti Ok. Will see how it goes live as an issue. Also, do you mind replying to [reddit](https://www.reddit.com/r/FlutterDev/comments/815fjp/does_flutter_support_in_app_purchases) since I am not using it? I want more people to use this plugin so that I can improve it.

**Comment by dooboolab** [comment] 2018-08-18 10:35
Will close this for now since it is related to https://github.com/dooboolab/flutter_inapp_purchase/issues/17.

**Closed by dooboolab** 2018-08-18 10:35 UTC
Labels: bug, help wanted

**Comment by Eneum** [comment] 2018-11-22 00:33
I got the same error in Camera Plugin, leading to a crash:

D/AndroidRuntime(10613): Shutting down VM
E/AndroidRuntime(10613): FATAL EXCEPTION: main
E/AndroidRuntime(10613): Process: com.eneum.android, PID: 10613
E/AndroidRuntime(10613): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(10613): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime(10613): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:203)
E/AndroidRuntime(10613): 	at io.flutter.plugins.camera.CameraPlugin$Camera$3.onOpened(CameraPlugin.java:481)
E/AndroidRuntime(10613): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:139)
E/AndroidRuntime(10613): 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime(10613): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(10613): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10613): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(10613): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10613): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(10613): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by dooboolab** [comment] 2018-11-22 01:47
@Eneum Hey what do you mean by the `camera` plugin? This isn't belong here.

**Comment by dark-chocolate** [comment] 2019-03-24 07:56
@hyochan I think this is a known [issue](https://github.com/flutter/flutter/issues/29092) when things (threading) are not done carefully.

**Comment by SAGARSURI** [comment] 2019-04-30 11:01
I am trying to build a messaging app. I am using method channels to send and receive messages. First time when I receive a message its working perfectly i.e passing the message from android to Flutter view using the MethodChannel. But the second it crashes resulting:
 
`java.lang.IllegalStateException: Reply already submitted`

Here is my android code:

`call.method == "receiveMessage" -> receiveMessage(result)`

```
private fun receiveMessage(result: MethodChannel.Result){
        val listenerID="com.sagar.gossip.MainActivity"

        MyChat.addMessageListener(listenerID, object : MyChat.MessageListener() {
            override fun onTextMessageReceived(p0: TextMessage?) {
                Log.d(TAG, "Message received successfully: " + p0?.toString())
                result.success(p0?.text)
            }
        })
    }
```

My Flutter code:
```
Future<String> receiveMessage() async {
    String message = '';
    try{
      message = await platform.invokeMethod('receiveMessage');
    } on PlatformException catch(e){
      message = e.message;
    }
    return message;
  }
```

**Comment by daybson** [comment] 2021-11-21 20:27
2021 same problem here:

E/AndroidRuntime(25903): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25903): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(25903): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(25903): 	at com.dooboolab.flutterinapppurchase.MethodResultWrapper$1.run(MethodResultWrapper.java:27)
E/AndroidRuntime(25903): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(25903): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25903): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(25903): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(25903): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25903): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(25903): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

main.dart
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  await Authentication.initFirebase();

  await MobileAds.instance.initialize();

  SharedPrefs.i.prefs = await SharedPreferences.getInstance();
  AdsService();
  await RemoteConfigService.i.loadRemoteConfigs();
  HomePage.packageInfo = await PackageInfo.fromPlatform();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  databaseVersion = SharedPrefs.i.prefs.getInt(Constants.DATABASE_VERSION);
  if (databaseVersion == null) {
    SharedPrefs.i.prefs.setInt(Constants.DATABASE_VERSION, -1);
    databaseVersion = -1;
  }
  await DatabaseHelper.instance.loadDatabase(databaseVersion);

  try {
    PaymentService.instance.initConnection();
  } catch (e) {
    print("ERROR >>>>> $e");
    PaymentService.instance.dispose();
  }
  runApp(
    GetMaterialApp(
      initialRoute: AppRoutes.HOME,
      theme: ThemeData(
          primaryColor: Colors.blue[900],
          appBarTheme: AppBarTheme(backgroundColor: Colors.blue[900])),
      getPages: AppPages.routes,
      builder: (BuildContext context, Widget widget) {
        var paddingBottom = 50.0;
        var height = MediaQuery.of(context).size.height;

        if (height <= 400) {
          paddingBottom = 32;
        } else if (height > 400 && height <= 720) {
          paddingBottom = 50;
        } else if (height > 720) {
          paddingBottom = 90;
        }

        return Column(
          children: [
            SizedBox(
              child: widget,
              height: height - paddingBottom,
            ),
            SizedBox(
              child: BannerInlinePage(),
              height: paddingBottom,
            ),
          ],
        );
      },
      onDispose: () async {
        await AdsService.i.disposeInterstitialAd();
        PaymentService.instance.dispose();
      },
    ),
  );
}

```

**Comment by valterh4ck3r** [comment] 2022-04-26 23:36
Same issue here using PaymentService of the documentation.

**Comment by Vakil-Parth** [comment] 2022-04-27 13:47
is this package abandoned?

**Comment by valterh4ck3r** [comment] 2022-04-27 13:52
Hello Guys.

Use my library with fix

https://github.com/valterh4ck3r/flutter_inapp_purchase

My fix: https://github.com/dooboolab/flutter_inapp_purchase/pull/356

Use this

`
  flutter_inapp_purchase:
    git: https://github.com/valterh4ck3r/flutter_inapp_purchase
`

**Comment by lukepighetti** [comment] 2022-04-27 14:39
PR related to above comment: https://github.com/dooboolab/flutter_inapp_purchase/pull/356

**Comment by ubitechparth** [comment] 2022-10-07 08:15
I got the same error in Simple S3 Plugin, leading to a crash:

D/AndroidRuntime( 8213): Shutting down VM
I/flutter ( 8213): updatedata line no1217
E/AndroidRuntime( 8213): FATAL EXCEPTION: main
E/AndroidRuntime( 8213): Process: org.ubitech.attendance, PID: 8213
E/AndroidRuntime( 8213): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 8213): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime( 8213): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 8213): 	at com.abhimortal6.simple_s3.SimpleS3Plugin$Transfer.onStateChanged(SimpleS3Plugin.java:279)
E/AndroidRuntime( 8213): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
E/AndroidRuntime( 8213): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8213): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8213): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8213): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime( 8213): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8213): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8213): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
I/flutter ( 8213): globals.attImage1.value line 1230
I/flutter ( 8213): 2131091
I/flutter ( 8213): globals.attImage1.value line 1232
I/tech.attendanc( 8213): Background concurrent copying GC freed 107195(4101KB) AllocSpace objects, 9(1300KB) LOS objects, 49% free, 12MB/24MB, paused 714us total 101.057ms
I/Process ( 8213): Sending signal. PID: 8213 SIG: 9
Lost connection to device.
