### ISSUE TITLE
flutter in app purchase doesn't show purchase window on ios

### ISSUE THREAD

**Issue by andeeDev** [dooboolab/flutter_inapp_purchase#305] opened 2021-08-03 13:17 UTC
### Version of flutter_inapp_purchase
Version 5.0.2
### Platforms you faced the error (IOS or Android or both?)
IOS platform
### Expected behavior
Show purchase window
### Actual behavior
Writing in console that purchase was successful
### Tested environment (Emulator? Real Device?)
Ipad 14.6
### Steps to reproduce the behavior
Add items in appstoreconnect

```
 List<IAPItem> purchaseList = <IAPItem>[];
  final List<String> _productIds = Platform.isAndroid
      ? <String>['subscription', 'test', 'test2', 'test4', 'test3']
      : <String>['TestSubscriptionId','test'];

 Map<String, dynamic> createPaymentMap(PurchasedItem productItem) {
    Map<String, dynamic> mapSubscription = <String, dynamic>{};

    mapSubscription['transactionReceipt'] = productItem.transactionReceipt;
    mapSubscription['productId'] = productItem.productId;
    mapSubscription['transactionId'] = productItem.transactionId;
    mapSubscription['purchaseToken'] = productItem.purchaseToken;
    mapSubscription['transactionDate'] =
        productItem.transactionDate.toString();
    mapSubscription['orderId'] = productItem.orderId;
    return mapSubscription;
  }
void initProducts() async {
    List<IAPItem> list =
    await FlutterInappPurchase.instance.getSubscriptions(_productIds);
  
    setState(() {
      purchaseList = list;
    });
  }
  
  void initStoreInfo() async {
    String str = await FlutterInappPurchase.instance.initConnection;

    _connectionSubscription = FlutterInappPurchase.connectionUpdated
        .listen((ConnectionResult connected) {
      print('##!connected: $connected');
    });
    _purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated
        .listen((PurchasedItem productItem) async {
      Map<String, dynamic> mapSubscription = createPaymentMap(productItem);
    });
    _purchaseErrorSubscription = FlutterInappPurchase.purchaseError
        .listen((PurchaseResult purchaseError) {
      print('purchase-error: $purchaseError');
    });
    initProducts();
  }
```

**Comment by Gambolico** [comment] 2021-08-05 08:21
I see a lot of things i dont understand:

Why do you transform PurchasedItem to a map? You dont need to do that. Also, where are you calling requestPurchase()? That method is the one that brings the paymentSheet.

Follow the example in the docs: [https://pub.dev/packages/flutter_inapp_purchase/example](url)

You will see that there after `_getProduct()`, he lists them and creates a button for each one of then with an `onPressed: () {
                        print("---------- Buy Item Button Pressed");
                        this._requestPurchase(item);
                      }`

**Comment by andeeDev** [comment] 2021-08-05 14:39
In my code I call requestSubscription after click on button, 
but, unfortunately, purchase window is not shown. Everything I had in console was message that payment was successful, but there was no sign of modal window with prompt to subscribe.

**Comment by alex-lechner** [comment] 2021-08-12 10:09
I have the same problem
Duplicate of #271

**Closed** 2021-11-19 01:04 UTC
Labels: no-issue-activity
